### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by sbkg0002**
### Description of change
Adds Dockerfile

### Pull-Request Checklist

- [X] Code is up-to-date with the `main` branch
- [ ]  This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by sbkg0002** [comment]
Example [here](docker.io/sbkg0002/aws-cost-cli).

**Comment by kamranahmedse** [comment]
Thank you for the PR but I don't think there is a need for that.

**Comment by console6500** [comment]
I was also looking for a Docker feature.  this would allow the application to be run in environments where `docker` is available but `npm` is not.

**Comment by sfunkernw** [comment]
Thank you @sbkg0002 . Without the Dockerfile I ran into exceptions after npm installing aws-cost-cli with Ubuntu 22 default nodejs package version 12.

**Comment by o6uoq** [comment]
I've created another PR to merge in, adding a Dockerfile and updates to the README.md on how to use. I hope you can re-evaluate the decision to use Docker, given the widespread and daily use of containers, we would love to see `aws-cost-cli` support a way to run via Docker.

**Pull request closed without merging**
